Repository 1Hive/apiary, pull requests merged in 2019-11, with the labels that each got.

#61 Use GitHub Actions CI
  .circleci/config.yml
  .github/workflows/api.yml
  .github/workflows/website.yml
  .github/workflows/worker.yml
Labels: enhancement

#76 Add Open Enterprise kit
  worker/src/org/kits.js
Labels: enhancement

#84 Implement template filter for organisations
  api/src/common/schema.js
  api/src/filter.js
  api/src/orgs/data.js
  api/src/orgs/schema.js
  website/src/components/Filter/Filter.js
  website/src/pages/orgs.js
Labels: enhancement

#68 Add code of conduct
  .github/CODE_OF_CONDUCT.md
  README.md
Labels: documentation, enhancement

#87 Add GitHub Actions badges in README
  README.md
Labels: documentation

#95 Remove references to Daolist in README
  README.md
Labels: code debt

#97 Run GitHub Actions on pull requests
  .github/workflows/api.yml
  .github/workflows/website.yml
  .github/workflows/worker.yml
Labels: enhancement

#101 Upgrade @aragon/ui to ^1.0.0
  website/package-lock.json
  website/package.json
  website/src/components/Filter/DateRangeFilter.js
Labels: dependencies
