Repository 1Hive/apiary, pull requests merged in 2020-05, with the labels that each got.

#181 Feature: Add DAO profiles
  api/package-lock.json
  api/package.json
  api/rollup.config.js
  api/src/abis/kernel.json
  api/src/apps/data.js
  api/src/orgs/data.js
  api/src/orgs/resolver.js
  api/src/orgs/schema.js
  api/src/pagination.js
  api/src/utils.js
  api/src/web3-utils.js
  docker-compose.yml
  heroku.yml
  website/package-lock.json
  website/package.json
  website/src/assets/dao-not-found.png
  website/src/components/Account/AccountButton.js
  website/src/components/Account/AccountModule.js
  website/src/components/Account/HeaderModule.js
  website/src/components/Account/HeaderPopover.js
  website/src/components/Account/ScreenConnected.js
  website/src/components/Account/ScreenConnecting.js
  website/src/components/Account/ScreenError.js
  website/src/components/Account/ScreenProviders.js
  website/src/components/Account/assets/connection-error.png
  website/src/components/Account/assets/loading-ring.svg
  website/src/components/AnimatedLogo/AnimatedLogo.js
  website/src/components/Filter/Filter.js
  website/src/components/LocalIdentityBadge/LocalIdentityBadge.js
  website/src/components/LocalIdentityBadge/LocalLabelPopoverActionLabel.js
  website/src/components/LocalIdentityBadge/LocalLabelPopoverTitle.js
  website/src/components/Logo.js
  website/src/components/SidePanel/EditSidePanel.js
  website/src/components/SidePanel/RejectionSidePanel.js
  website/src/components/SidePanel/TransactionSidePanel.js
  website/src/components/SmartLink/SmartLink.js
  website/src/components/WindowedPagination/WindowedPagination.js
  website/src/ethereum-providers/icons/Cipher.png
  website/src/ethereum-providers/icons/Fortmatic.svg
  website/src/ethereum-providers/icons/Frame.png
  website/src/ethereum-providers/icons/Metamask.png
  website/src/ethereum-providers/icons/Portis.svg
  website/src/ethereum-providers/icons/Status.png
  website/src/ethereum-providers/icons/wallet.svg
  website/src/ethereum-providers/index.js
  website/src/hooks/useCopyToClipboard.js
  website/src/index.js
  website/src/pages/app.js
  website/src/pages/apps.js
  website/src/pages/orgs.js
  website/src/pages/profile.js
  website/src/utils/ownership-statuses.js
  website/src/utils/utils.js
  website/src/utils/web3-contracts.js
  website/src/utils/web3-utils.js
Labels: enhancement

#187 Add filter to show only orgs with profiles
  api/src/filter.js
  api/src/orgs/data.js
  api/src/orgs/schema.js
  website/src/components/Filter/CheckboxFilter.js
  website/src/components/Filter/Filter.js
  website/src/components/Filter/ListFilter.js
  website/src/components/Filter/index.js
  website/src/pages/orgs.js
Labels: enhancement

#186 Add app repository name to app list
  api/src/apps/schema.js
  website/src/pages/apps.js
Labels: enhancement

#190 Fix placeholders in list filters
  website/src/components/Filter/ListFilter.js
Labels: bug

#185 Performance and stability
  taskmaster/package-lock.json
  taskmaster/package.json
  taskmaster/src/index.js
  worker/package-lock.json
  worker/package.json
  worker/src/cache.js
  worker/src/db.js
  worker/src/eth/data.js
  worker/src/eth/index.js
  worker/src/eth/logs.js
  worker/src/eth/transactions.js
  worker/src/handlers/app.js
  worker/src/handlers/org.js
  worker/src/index.js
  worker/src/utils/task-deps.js
Labels: code debt, enhancement

#193 Default back button on profile page to overview
  website/src/pages/profile.js
Labels: bug

#194 Minor cosmetic adjustments to organisation profiles
  website/src/pages/profile.js
Labels: enhancement
