Repository 1Hive/apiary, pull requests merged in 2020-01, with the labels that each got.

#112 Specify node version for website
  website/package.json
Labels: documentation

#116 App context filter
  website/src/pages/apps.js
  website/src/pages/orgs.js
Labels: enhancement

#117 Upgrade to Node 12
  api/Dockerfile.web
  website/Dockerfile.frontend
  worker/Dockerfile.worker
Labels: code debt

#122 Only format Very Large Numbers:tm:
  website/src/utils/numbers.js
Labels: enhancement

#130 Add Taskmaster to Docker Compose
  docker-compose.yml
Labels: enhancement

#132 Add Fundraising kit
  website/src/pages/orgs.js
  worker/src/org/kits.js
Labels: enhancement

#131 Add AUM, activity and organisation/app score
  api/src/orgs/schema.js
  website/src/components/SortHeader/SortHeader.js
  website/src/pages/apps.js
  website/src/pages/orgs.js
Labels: enhancement

#134 App score tweaks
  worker/package-lock.json
  worker/package.json
  worker/rollup.config.js
  worker/src/task/app-scores.js
Labels: enhancement

#135 Format AUM
  website/src/pages/orgs.js
Labels: enhancement

#136 Return 0 for ANT/AUM/activity if there is no record
  api/src/apps/resolver.js
  api/src/orgs/resolver.js
Labels: enhancement

#140 Ignore unindexed apps in app score calculation
  worker/src/task/app-scores.js
Labels: bug

#141 Count activity once per transaction per org
  worker/src/task/app-scores.js
Labels: enhancement
