Repository 1Hive/apiary, pull requests merged in 2020-02, with the labels that each got.

#147 Handle malformed organization names
  worker/src/org/name.js
Labels: bug

#146 Migrate to new trace structure
  worker/src/eth/traces.js
Labels: enhancement

#145 Improve API documentation on environment variables
  README.md
Labels: documentation

#151 Mark `score`, `ant`, `aum` as required in schema
  api/src/orgs/resolver.js
  api/src/orgs/schema.js
Labels: enhancement

#148 Default to sorting descending
  website/src/hooks/sort.js
Labels: enhancement

#152 Fix timestamps
  worker/src/app/install.js
  worker/src/org/name.js
Labels: bug

#153 Add temporary maintenance notice
  website/src/pages/app.js
Labels: enhancement

#154 Add Dandelion template
  website/src/pages/orgs.js
  worker/src/org/kits.js
Labels: enhancement

#155 Remove eth events blockhash
  worker/src/db.js
  worker/src/eth/traces.js
Labels: code debt

#156 Ensure addresses in activities are checksummed
  worker/src/activity/persist.js
  worker/src/eth/traces.js
Labels: bug

#166 Add ANT to GraphQL API
  api/src/orgs/resolver.js
  api/src/orgs/schema.js
Labels: enhancement

#167 Add organisation app proxies to the GraphQL schema
  api/src/apps/data.js
  api/src/proxies/resolver.js
  api/src/proxies/schema.js
  api/src/resolvers.js
  api/src/schema.js
Labels: enhancement

#168 Add app score calculation CLI script
  scripts/calcscore
  scripts/package-lock.json
  scripts/package.json
Labels: enhancement

#149 Format all numbers consistently (using toLocaleString)
  website/src/pages/apps.js
  website/src/pages/orgs.js
  website/src/utils/numbers.js
Labels: enhancement
